version: '3'
services:
  bmcook:
    build:
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGPASSWORD: ${POSTGRES_PASSWORD}
      context: .
    environment:
      PYTHONUNBUFFERED: 1
      POSTGRES_USER:
      POSTGRES_HOST:
      POSTGRES_DATABASE:
      POSTGRES_PORT:
      POSTGRES_PASSWORD:
      PGPASSWORD: ${POSTGRES_PASSWORD}
      BMCOOK_HTTPS_PORT:

    ports:
      - ${BMCOOK_HTTPS_PORT}:8000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./test-results/:/tmp/test-results/

  db:
    image: postgres:15
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    shm_size: 4gb
