version: '3'
services:
  bmcook:
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: 1
      PG_USER:
      PG_PASSWORD:
      PG_HOST:
      PG_DB:
      PG_PORT:
      PG_PASS:
      BMCOOK_HTTPS_PORT:

    ports:
      - ${BMCOOK_HTTPS_PORT}:8000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./test-results/:/tmp/test-results/

  db:
    image: postgres:15
    environment:
      PG_USER:
      PG_PASSWORD:
    ports:
      - ${PG_PORT}:5432
    restart: always
    shm_size: 4gb
